### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by brandonkal** [hex-ci/vscode-stylelint-plus#1]
It is unclear why (as the large formatting-only changes makes comparison difficult), but this fork appears to fix an issue where the main extension does not show lint messages.

Please consider:
1. Reverting all the style-only changes. This just makes diffing extremely difficult.
2. Adding a command to run run the equivalent of `stylelint --fix`.

**Comment by phyllisstein** [comment]
Just here to echo the thanks, especially for adding the `css-in-js` syntax flag. ♥️
