### ISSUE TITLE
stylelint: Invalid option name "ignoreSelectors" for rule "property-no-unknown"

### ISSUE THREAD

**Issue by JustFly1984** [hex-ci/vscode-stylelint-plus#11]
Getting this issue while trying to update stylelint from 10 to 12 version. Please update stylelint version.

**Comment by johnhunter** [comment]
See issue raised https://github.com/stylelint/stylelint/issues/4403#issuecomment-552082019
The plugin is incompatible with current stylelint config files.

**Comment by kroko** [comment]
switching to actively maintained _official_ [stylelint/vscode-stylelint](https://github.com/stylelint/vscode-stylelint) solves it. see also https://github.com/hex-ci/vscode-stylelint-plus/issues/18
