### ISSUE TITLE
Error: You must pass stylelint a `files` glob or a `code` string

### ISSUE THREAD

**Issue by OliverJAsh** [hex-ci/vscode-stylelint-plus#13]
1. Open a new VS Code window
2. Open a new tab for a new empty file

I see this error (even before opening any files):

<img width="1792" alt="Screenshot 2019-11-29 at 10 39 26" src="https://user-images.githubusercontent.com/921609/69863362-87248a00-1294-11ea-9401-441e6d0e3dc7.png">

```
Error: You must pass stylelint a `files` glob or a `code` string, though not both at module.exports (/Users/oliverash/.vscode/extensions/hex-ci.stylelint-plus-0.52.3/node_modules/stylelint/lib/standalone.js:73:11) at stylelintVSCode (/Users/oliverash/.vscode/extensions/hex-ci.stylelint-plus-0.52.3/stylelint-vscode.js:129:29) at validate (/Users/oliverash/.vscode/extensions/hex-ci.stylelint-plus-0.52.3/server.js:55:26)
```

The only configuration I have is `"stylelint.enable": true`.

**Comment by tjx666** [comment]
Also in quokka
![Snipaste_2019-12-01_11-57-05](https://user-images.githubusercontent.com/41773861/69909159-c20ff480-1431-11ea-92b1-337a4c6e468b.png)

**Comment by silkyfray** [comment]
I am experiencing the same issue

**Comment by OliverJAsh** [comment]
@hex-ci I don't see how this is related to #4. 

The only configuration I have is `"stylelint.enable": true`.

**Comment by OliverJAsh** [comment]
Upgrading didn't help, but it's fixed in the official extension.
