### ISSUE TITLE
stylelint: Undefined rule unicode-bom

### ISSUE THREAD

**Issue by vvpvvp** [hex-ci/vscode-stylelint-plus#23]
一直报错
stylelint: Undefined rule unicode-bom
![image](https://user-images.githubusercontent.com/7303371/94222754-d5d89a00-ff20-11ea-851a-c2aca810a09c.png)

**Comment by FDiskas** [comment]
Translation: This stylelint version should be too low, you can use the useLocal option to use the latest stylelint in your node_modules directory
