### ISSUE TITLE
Bump version of stylelint dependency

### ISSUE THREAD

**Issue by mikkelsandberg** [hex-ci/vscode-stylelint-plus#24]
This is related to [Handle object shorthand #67](https://github.com/gucong3000/postcss-jsx/pull/67) (which was merged into stylelint in [Bump postcss-jsx to 0.36.4 #4550](https://github.com/stylelint/stylelint/pull/4550))
We're noticing in cases where using the `style` prop in components that object shorthand is being automatically changed to `style={{height:height}}`, for example. Interestingly enough, `postcss-jsx` was removed from stylelint in [Replace syntaxes with our forks #4685](https://github.com/stylelint/stylelint/pull/4685) in 13.3.1, but the current version of stylelint is 13.7.2 so perhaps that version should be targeted.

**Comment by fuhlig** [comment]
> This stylelint version should be too low, you can use the useLocal option to use the latest stylelint in your node_modules directory

This does not consider a monorepo structure.
When linting `package/myPackage/style.css` the extension is looking for `package/node_modules/stylelint` instead of the root level `node_modules/stylelint`.

**Comment by fuhlig** [comment]
Yes because the modules are not installed in the packages but in the root folder and cwn not be located by the extension. 

It works with the official vscode extension (by stylelint) out of the box and also provides additional options for stylelint executable path.
