### ISSUE TITLE
Add support for stylelint rule `declaration-block-no-duplicate-custom-properties`?

### ISSUE THREAD

**Issue by Flcwl** [hex-ci/vscode-stylelint-plus#31]
The Vscode will apear such error if I Added: declaration-block-no-duplicate-custom-properties rule.

```error
stylelint undefined rule declaration-block-no-duplicate-custom-properties
```

**Comment by Flcwl** [comment]
Oh, thx~ If I do it and it will automatically load the Stylelint installed in my project workspace or the global stylelint plugin  I need install `npm i -g stylelint`？

**Comment by Flcwl** [comment]
It's a pity that I try it But not work for me~

**Comment by stolinski** [comment]
I still have this issue using the stylelint@latest and using the local option in the plugin.
