### ISSUE TITLE
Unknown rule custom-property-no-missing-var-function.

### ISSUE THREAD

**Issue by kimzeevaarders** [hex-ci/vscode-stylelint-plus#32]
Hi,

since we upgraded ouyr stylelint packages (a.o. stylelint v14.1.0) we get the same error in the problem pane of VS code for each and everyone of our scss files. Because of this "ghost" error all scss files are treated erroneous by VS code.

However, when executing stylelint over the command line (`npx stylelint **/*.scss`), the error is not thrown and everything is fine.

See attached screenshot of the issue and the package.json of our React/Typescript project:

![Screenshot 2021-12-06 at 08 13 50](https://user-images.githubusercontent.com/3235117/144804492-c790e80a-6ad4-4475-b982-2ceba4645b7c.png)

![Screenshot 2021-12-06 at 08 21 40](https://user-images.githubusercontent.com/3235117/144804498-96bf0ea4-cad6-432b-8859-eef1cabfe4ae.png)

The issue is also mentioned here, but mistakenly reported in the wrong project: https://githubmemory.com/repo/stylelint/vscode-stylelint/issues/276

**Comment by kimzeevaarders** [comment]
ah ok, thx! Will this support come in the future?

**Comment by toimc** [comment]
同样的问题，这个问题怎么解决呢？看你的源码代码没有思路，想帮个忙~
