### ISSUE TITLE
Unknown word (CssSyntaxError)stylelint(CssSyntaxError)

### ISSUE THREAD

**Issue by bikashd003** [hex-ci/vscode-stylelint-plus#35]
a new issue occurs on every code file, whether it is simple boilerplate code or complex code, the issue is 
"Unknown word (CssSyntaxError)stylelint(CssSyntaxError)"

**Comment by BohdanYavorskyi** [comment]
@hex-ci it just doesn't make any sense. All jsx, tsx files are scanned (not styles) and error. Please take a look at what can break it and try to fix. Thanks in advance.

**Comment by BohdanYavorskyi** [comment]
> > @hex-ci it just doesn't make any sense. All jsx, tsx files are scanned (not styles) and error. Please take a look at what can break it and try to fix. Thanks in advance.
> 
> Please use `useLocal` option.

if I don't have local configuration. Where this one should be added?

**Comment by time4nothing** [comment]
I am also having this problem since updating to stylelint-plus v0.57.0. Problem goes away if I install the previous version v0.56.6. Will this bug be fixed soon?

**Comment by sanket95droid** [comment]
not able to downgrade to stylelint v13 please help?

**Comment by sanket95droid** [comment]
> > I am also having this problem since updating to stylelint-plus v0.57.0. Problem goes away if I install the previous version v0.56.6. Will this bug be fixed soon?
> 
> Downgrading is not a good idea. Because the latest version of stylelint is now v16, v17 may come soon. We can't always use a very old version of stylelint. If you want to use an old version of stylelint, please turn on the `useLocal` option to use stylelint in your own project directory.

what actually  is useLocal and where to use it, can you provide reference to any docs?
Thank you
