### ISSUE TITLE
Use locally installed stylelint package

### ISSUE THREAD

**Issue by axelboc** [hex-ci/vscode-stylelint-plus#7]
Is there any way the extension could use the local `stylelint` package from the currently open project? I believe other extensions work this way to simplify version management.

**Comment by remcohaszing** [comment]
The extensions [ESLint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) and [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) work this way.
