### ISSUE TITLE
"stylelint: Undefined rule unicode-bom"

### ISSUE THREAD

**Issue by timmyomahony** [hex-ci/vscode-stylelint-plus#8]
I'm using this plugin having come from the shinnn version. My stylelint looks like:

```
{
  "extends": "stylelint-config-twbs-bootstrap/scss",
  "rules": {
    "selector-class-pattern": "^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$",
    "declaration-no-important": null,
    "scss/dollar-variable-default": null,
    "color-hex-length": "long",
    "block-no-empty": null,
    "value-list-comma-newline-after": "always-multi-line",
    "value-list-comma-space-after": "always-single-line"
  }
}
```

and my `package.json`:

```
"stylelint": "^12.0.0",
"stylelint-config-twbs-bootstrap": "^0.9.0",
```

I'm getting the error:

> stylelint: Undefined rule unicode-bom

When I run stylelint. The issue (I assume) is that this extension is using its own internal version of stylelint that is < 12.0.0. 

Stylelint added support for this rule `unicode-bom` in version 12:

https://github.com/stylelint/stylelint/issues/4228
https://github.com/stylelint/stylelint/blob/master/CHANGELOG.md#1200

I can confirm that there is nothing wrong with my config or setup, as I'm able to run stylelint as a regular `gulp` task from my `node_modules` and it works perfectly. It seems the issue is that this extension is using its own version of stylling. 

Is it possible to use our own `node_modules` version of styleline?

**Comment by SnO2WMaN** [comment]
+1

I think this problem is serious and should be resolved as soon as possible.

**Comment by skorunka** [comment]
Yep, very obstructing issue in deed :(. Cheers for quick fix guys.

**Comment by THernandez03** [comment]
It seems PR #5 fixes this issue
